//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TrafficAllocation.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TrafficAllocationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TrafficAllocationEntities object using the connection string found in the 'TrafficAllocationEntities' section of the application configuration file.
        /// </summary>
        public TrafficAllocationEntities() : base("name=TrafficAllocationEntities", "TrafficAllocationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrafficAllocationEntities object.
        /// </summary>
        public TrafficAllocationEntities(string connectionString) : base(connectionString, "TrafficAllocationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TrafficAllocationEntities object.
        /// </summary>
        public TrafficAllocationEntities(EntityConnection connection) : base(connection, "TrafficAllocationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NetworkViewSlice> NetworkViewSlices
        {
            get
            {
                if ((_NetworkViewSlices == null))
                {
                    _NetworkViewSlices = base.CreateObjectSet<NetworkViewSlice>("NetworkViewSlices");
                }
                return _NetworkViewSlices;
            }
        }
        private ObjectSet<NetworkViewSlice> _NetworkViewSlices;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NetworkViewSlices EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNetworkViewSlices(NetworkViewSlice networkViewSlice)
        {
            base.AddObject("NetworkViewSlices", networkViewSlice);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<GetFlightCubeDataResult> sp_GetFlightCubeData()
        {
            return base.ExecuteFunction<GetFlightCubeDataResult>("sp_GetFlightCubeData");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TrafficAllocationModel", Name="NetworkViewSlice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NetworkViewSlice : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NetworkViewSlice object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static NetworkViewSlice CreateNetworkViewSlice(global::System.Int32 id)
        {
            NetworkViewSlice networkViewSlice = new NetworkViewSlice();
            networkViewSlice.ID = id;
            return networkViewSlice;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ViewName
        {
            get
            {
                return _ViewName;
            }
            set
            {
                OnViewNameChanging(value);
                ReportPropertyChanging("ViewName");
                _ViewName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ViewName");
                OnViewNameChanged();
            }
        }
        private global::System.String _ViewName;
        partial void OnViewNameChanging(global::System.String value);
        partial void OnViewNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Network
        {
            get
            {
                return _Network;
            }
            set
            {
                OnNetworkChanging(value);
                ReportPropertyChanging("Network");
                _Network = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Network");
                OnNetworkChanged();
            }
        }
        private global::System.String _Network;
        partial void OnNetworkChanging(global::System.String value);
        partial void OnNetworkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Partner
        {
            get
            {
                return _Partner;
            }
            set
            {
                OnPartnerChanging(value);
                ReportPropertyChanging("Partner");
                _Partner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Partner");
                OnPartnerChanged();
            }
        }
        private global::System.String _Partner;
        partial void OnPartnerChanging(global::System.String value);
        partial void OnPartnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _Country;
            }
            set
            {
                OnCountryChanging(value);
                ReportPropertyChanging("Country");
                _Country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Country");
                OnCountryChanged();
            }
        }
        private global::System.String _Country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Medium
        {
            get
            {
                return _Medium;
            }
            set
            {
                OnMediumChanging(value);
                ReportPropertyChanging("Medium");
                _Medium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Medium");
                OnMediumChanged();
            }
        }
        private global::System.String _Medium;
        partial void OnMediumChanging(global::System.String value);
        partial void OnMediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Device
        {
            get
            {
                return _Device;
            }
            set
            {
                OnDeviceChanging(value);
                ReportPropertyChanging("Device");
                _Device = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Device");
                OnDeviceChanged();
            }
        }
        private global::System.String _Device;
        partial void OnDeviceChanging(global::System.String value);
        partial void OnDeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActaullViewName
        {
            get
            {
                return _ActaullViewName;
            }
            set
            {
                OnActaullViewNameChanging(value);
                ReportPropertyChanging("ActaullViewName");
                _ActaullViewName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActaullViewName");
                OnActaullViewNameChanged();
            }
        }
        private global::System.String _ActaullViewName;
        partial void OnActaullViewNameChanging(global::System.String value);
        partial void OnActaullViewNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Int32> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Int32> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ViewSliceName
        {
            get
            {
                return _ViewSliceName;
            }
            set
            {
                OnViewSliceNameChanging(value);
                ReportPropertyChanging("ViewSliceName");
                _ViewSliceName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ViewSliceName");
                OnViewSliceNameChanged();
            }
        }
        private global::System.String _ViewSliceName;
        partial void OnViewSliceNameChanging(global::System.String value);
        partial void OnViewSliceNameChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrafficAllocationModel", Name="FlightCubeDataResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class FlightCubeDataResult : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> day
        {
            get
            {
                return _day;
            }
            set
            {
                OndayChanging(value);
                ReportPropertyChanging("day");
                _day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day");
                OndayChanged();
            }
        }
        private Nullable<global::System.Int64> _day;
        partial void OndayChanging(Nullable<global::System.Int64> value);
        partial void OndayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String flight
        {
            get
            {
                return _flight;
            }
            set
            {
                OnflightChanging(value);
                ReportPropertyChanging("flight");
                _flight = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("flight");
                OnflightChanged();
            }
        }
        private global::System.String _flight;
        partial void OnflightChanging(global::System.String value);
        partial void OnflightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExperimentName
        {
            get
            {
                return _ExperimentName;
            }
            set
            {
                OnExperimentNameChanging(value);
                ReportPropertyChanging("ExperimentName");
                _ExperimentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExperimentName");
                OnExperimentNameChanged();
            }
        }
        private global::System.String _ExperimentName;
        partial void OnExperimentNameChanging(global::System.String value);
        partial void OnExperimentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String medium
        {
            get
            {
                return _medium;
            }
            set
            {
                OnmediumChanging(value);
                ReportPropertyChanging("medium");
                _medium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("medium");
                OnmediumChanged();
            }
        }
        private global::System.String _medium;
        partial void OnmediumChanging(global::System.String value);
        partial void OnmediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String device
        {
            get
            {
                return _device;
            }
            set
            {
                OndeviceChanging(value);
                ReportPropertyChanging("device");
                _device = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("device");
                OndeviceChanged();
            }
        }
        private global::System.String _device;
        partial void OndeviceChanging(global::System.String value);
        partial void OndeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> revenue
        {
            get
            {
                return _revenue;
            }
            set
            {
                OnrevenueChanging(value);
                ReportPropertyChanging("revenue");
                _revenue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("revenue");
                OnrevenueChanged();
            }
        }
        private Nullable<global::System.Decimal> _revenue;
        partial void OnrevenueChanging(Nullable<global::System.Decimal> value);
        partial void OnrevenueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> impressions
        {
            get
            {
                return _impressions;
            }
            set
            {
                OnimpressionsChanging(value);
                ReportPropertyChanging("impressions");
                _impressions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impressions");
                OnimpressionsChanged();
            }
        }
        private Nullable<global::System.Int64> _impressions;
        partial void OnimpressionsChanging(Nullable<global::System.Int64> value);
        partial void OnimpressionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> clicks
        {
            get
            {
                return _clicks;
            }
            set
            {
                OnclicksChanging(value);
                ReportPropertyChanging("clicks");
                _clicks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clicks");
                OnclicksChanged();
            }
        }
        private Nullable<global::System.Int64> _clicks;
        partial void OnclicksChanging(Nullable<global::System.Int64> value);
        partial void OnclicksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> srpv
        {
            get
            {
                return _srpv;
            }
            set
            {
                OnsrpvChanging(value);
                ReportPropertyChanging("srpv");
                _srpv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("srpv");
                OnsrpvChanged();
            }
        }
        private Nullable<global::System.Int64> _srpv;
        partial void OnsrpvChanging(Nullable<global::System.Int64> value);
        partial void OnsrpvChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrafficType
        {
            get
            {
                return _TrafficType;
            }
            set
            {
                OnTrafficTypeChanging(value);
                ReportPropertyChanging("TrafficType");
                _TrafficType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrafficType");
                OnTrafficTypeChanged();
            }
        }
        private global::System.String _TrafficType;
        partial void OnTrafficTypeChanging(global::System.String value);
        partial void OnTrafficTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentType
        {
            get
            {
                return _EnvironmentType;
            }
            set
            {
                OnEnvironmentTypeChanging(value);
                ReportPropertyChanging("EnvironmentType");
                _EnvironmentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnvironmentType");
                OnEnvironmentTypeChanged();
            }
        }
        private global::System.String _EnvironmentType;
        partial void OnEnvironmentTypeChanging(global::System.String value);
        partial void OnEnvironmentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pub_owner
        {
            get
            {
                return _pub_owner;
            }
            set
            {
                Onpub_ownerChanging(value);
                ReportPropertyChanging("pub_owner");
                _pub_owner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pub_owner");
                Onpub_ownerChanged();
            }
        }
        private global::System.String _pub_owner;
        partial void Onpub_ownerChanging(global::System.String value);
        partial void Onpub_ownerChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="TrafficAllocationModel", Name="GetFlightCubeDataResult")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetFlightCubeDataResult : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String day
        {
            get
            {
                return _day;
            }
            set
            {
                OndayChanging(value);
                ReportPropertyChanging("day");
                _day = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("day");
                OndayChanged();
            }
        }
        private global::System.String _day;
        partial void OndayChanging(global::System.String value);
        partial void OndayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String flight
        {
            get
            {
                return _flight;
            }
            set
            {
                OnflightChanging(value);
                ReportPropertyChanging("flight");
                _flight = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("flight");
                OnflightChanged();
            }
        }
        private global::System.String _flight;
        partial void OnflightChanging(global::System.String value);
        partial void OnflightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExperimentName
        {
            get
            {
                return _ExperimentName;
            }
            set
            {
                OnExperimentNameChanging(value);
                ReportPropertyChanging("ExperimentName");
                _ExperimentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExperimentName");
                OnExperimentNameChanged();
            }
        }
        private global::System.String _ExperimentName;
        partial void OnExperimentNameChanging(global::System.String value);
        partial void OnExperimentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrafficType
        {
            get
            {
                return _TrafficType;
            }
            set
            {
                OnTrafficTypeChanging(value);
                ReportPropertyChanging("TrafficType");
                _TrafficType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrafficType");
                OnTrafficTypeChanged();
            }
        }
        private global::System.String _TrafficType;
        partial void OnTrafficTypeChanging(global::System.String value);
        partial void OnTrafficTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EnvironmentType
        {
            get
            {
                return _EnvironmentType;
            }
            set
            {
                OnEnvironmentTypeChanging(value);
                ReportPropertyChanging("EnvironmentType");
                _EnvironmentType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EnvironmentType");
                OnEnvironmentTypeChanged();
            }
        }
        private global::System.String _EnvironmentType;
        partial void OnEnvironmentTypeChanging(global::System.String value);
        partial void OnEnvironmentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pub_owner
        {
            get
            {
                return _pub_owner;
            }
            set
            {
                Onpub_ownerChanging(value);
                ReportPropertyChanging("pub_owner");
                _pub_owner = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pub_owner");
                Onpub_ownerChanged();
            }
        }
        private global::System.String _pub_owner;
        partial void Onpub_ownerChanging(global::System.String value);
        partial void Onpub_ownerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String medium
        {
            get
            {
                return _medium;
            }
            set
            {
                OnmediumChanging(value);
                ReportPropertyChanging("medium");
                _medium = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("medium");
                OnmediumChanged();
            }
        }
        private global::System.String _medium;
        partial void OnmediumChanging(global::System.String value);
        partial void OnmediumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String device
        {
            get
            {
                return _device;
            }
            set
            {
                OndeviceChanging(value);
                ReportPropertyChanging("device");
                _device = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("device");
                OndeviceChanged();
            }
        }
        private global::System.String _device;
        partial void OndeviceChanging(global::System.String value);
        partial void OndeviceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> revenue
        {
            get
            {
                return _revenue;
            }
            set
            {
                OnrevenueChanging(value);
                ReportPropertyChanging("revenue");
                _revenue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("revenue");
                OnrevenueChanged();
            }
        }
        private Nullable<global::System.Decimal> _revenue;
        partial void OnrevenueChanging(Nullable<global::System.Decimal> value);
        partial void OnrevenueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> impressions
        {
            get
            {
                return _impressions;
            }
            set
            {
                OnimpressionsChanging(value);
                ReportPropertyChanging("impressions");
                _impressions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impressions");
                OnimpressionsChanged();
            }
        }
        private Nullable<global::System.Int64> _impressions;
        partial void OnimpressionsChanging(Nullable<global::System.Int64> value);
        partial void OnimpressionsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> clicks
        {
            get
            {
                return _clicks;
            }
            set
            {
                OnclicksChanging(value);
                ReportPropertyChanging("clicks");
                _clicks = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clicks");
                OnclicksChanged();
            }
        }
        private Nullable<global::System.Int64> _clicks;
        partial void OnclicksChanging(Nullable<global::System.Int64> value);
        partial void OnclicksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> srpv
        {
            get
            {
                return _srpv;
            }
            set
            {
                OnsrpvChanging(value);
                ReportPropertyChanging("srpv");
                _srpv = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("srpv");
                OnsrpvChanged();
            }
        }
        private Nullable<global::System.Int64> _srpv;
        partial void OnsrpvChanging(Nullable<global::System.Int64> value);
        partial void OnsrpvChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PagePlacement
        {
            get
            {
                return _PagePlacement;
            }
            set
            {
                OnPagePlacementChanging(value);
                ReportPropertyChanging("PagePlacement");
                _PagePlacement = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PagePlacement");
                OnPagePlacementChanged();
            }
        }
        private global::System.String _PagePlacement;
        partial void OnPagePlacementChanging(global::System.String value);
        partial void OnPagePlacementChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FeatureAreaType
        {
            get
            {
                return _FeatureAreaType;
            }
            set
            {
                OnFeatureAreaTypeChanging(value);
                ReportPropertyChanging("FeatureAreaType");
                _FeatureAreaType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FeatureAreaType");
                OnFeatureAreaTypeChanged();
            }
        }
        private global::System.String _FeatureAreaType;
        partial void OnFeatureAreaTypeChanging(global::System.String value);
        partial void OnFeatureAreaTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> rpm
        {
            get
            {
                return _rpm;
            }
            set
            {
                OnrpmChanging(value);
                ReportPropertyChanging("rpm");
                _rpm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rpm");
                OnrpmChanged();
            }
        }
        private Nullable<global::System.Decimal> _rpm;
        partial void OnrpmChanging(Nullable<global::System.Decimal> value);
        partial void OnrpmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> impressionYield
        {
            get
            {
                return _impressionYield;
            }
            set
            {
                OnimpressionYieldChanging(value);
                ReportPropertyChanging("impressionYield");
                _impressionYield = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("impressionYield");
                OnimpressionYieldChanged();
            }
        }
        private Nullable<global::System.Decimal> _impressionYield;
        partial void OnimpressionYieldChanging(Nullable<global::System.Decimal> value);
        partial void OnimpressionYieldChanged();

        #endregion
    }

    #endregion
    
}
