//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TrafficAllocation.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FlightCubeDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FlightCubeDBEntities object using the connection string found in the 'FlightCubeDBEntities' section of the application configuration file.
        /// </summary>
        public FlightCubeDBEntities() : base("name=FlightCubeDBEntities", "FlightCubeDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightCubeDBEntities object.
        /// </summary>
        public FlightCubeDBEntities(string connectionString) : base(connectionString, "FlightCubeDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FlightCubeDBEntities object.
        /// </summary>
        public FlightCubeDBEntities(EntityConnection connection) : base(connection, "FlightCubeDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TrafficAllocationDashboardDate> TrafficAllocationDashboardDates
        {
            get
            {
                if ((_TrafficAllocationDashboardDates == null))
                {
                    _TrafficAllocationDashboardDates = base.CreateObjectSet<TrafficAllocationDashboardDate>("TrafficAllocationDashboardDates");
                }
                return _TrafficAllocationDashboardDates;
            }
        }
        private ObjectSet<TrafficAllocationDashboardDate> _TrafficAllocationDashboardDates;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TrafficAllocationDashboardDates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrafficAllocationDashboardDates(TrafficAllocationDashboardDate trafficAllocationDashboardDate)
        {
            base.AddObject("TrafficAllocationDashboardDates", trafficAllocationDashboardDate);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FlightCubeDBModel", Name="TrafficAllocationDashboardDate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrafficAllocationDashboardDate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TrafficAllocationDashboardDate object.
        /// </summary>
        /// <param name="datekey">Initial value of the datekey property.</param>
        public static TrafficAllocationDashboardDate CreateTrafficAllocationDashboardDate(global::System.String datekey)
        {
            TrafficAllocationDashboardDate trafficAllocationDashboardDate = new TrafficAllocationDashboardDate();
            trafficAllocationDashboardDate.datekey = datekey;
            return trafficAllocationDashboardDate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String datekey
        {
            get
            {
                return _datekey;
            }
            set
            {
                if (_datekey != value)
                {
                    OndatekeyChanging(value);
                    ReportPropertyChanging("datekey");
                    _datekey = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("datekey");
                    OndatekeyChanged();
                }
            }
        }
        private global::System.String _datekey;
        partial void OndatekeyChanging(global::System.String value);
        partial void OndatekeyChanged();

        #endregion
    
    }

    #endregion
    
}
